// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: word2animal.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Word2Animal_GetAnimal_FullMethodName = "/brainball.word2animal.Word2Animal/GetAnimal"
)

// Word2AnimalClient is the client API for Word2Animal service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Word2AnimalClient interface {
	// GetAnimal returns the animal identifier for the given text.
	GetAnimal(ctx context.Context, in *GetAnimalRequest, opts ...grpc.CallOption) (*GetAnimalResponse, error)
}

type word2AnimalClient struct {
	cc grpc.ClientConnInterface
}

func NewWord2AnimalClient(cc grpc.ClientConnInterface) Word2AnimalClient {
	return &word2AnimalClient{cc}
}

func (c *word2AnimalClient) GetAnimal(ctx context.Context, in *GetAnimalRequest, opts ...grpc.CallOption) (*GetAnimalResponse, error) {
	out := new(GetAnimalResponse)
	err := c.cc.Invoke(ctx, Word2Animal_GetAnimal_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Word2AnimalServer is the server API for Word2Animal service.
// All implementations must embed UnimplementedWord2AnimalServer
// for forward compatibility
type Word2AnimalServer interface {
	// GetAnimal returns the animal identifier for the given text.
	GetAnimal(context.Context, *GetAnimalRequest) (*GetAnimalResponse, error)
	mustEmbedUnimplementedWord2AnimalServer()
}

// UnimplementedWord2AnimalServer must be embedded to have forward compatible implementations.
type UnimplementedWord2AnimalServer struct {
}

func (UnimplementedWord2AnimalServer) GetAnimal(context.Context, *GetAnimalRequest) (*GetAnimalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAnimal not implemented")
}
func (UnimplementedWord2AnimalServer) mustEmbedUnimplementedWord2AnimalServer() {}

// UnsafeWord2AnimalServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Word2AnimalServer will
// result in compilation errors.
type UnsafeWord2AnimalServer interface {
	mustEmbedUnimplementedWord2AnimalServer()
}

func RegisterWord2AnimalServer(s grpc.ServiceRegistrar, srv Word2AnimalServer) {
	s.RegisterService(&Word2Animal_ServiceDesc, srv)
}

func _Word2Animal_GetAnimal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAnimalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Word2AnimalServer).GetAnimal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Word2Animal_GetAnimal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Word2AnimalServer).GetAnimal(ctx, req.(*GetAnimalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Word2Animal_ServiceDesc is the grpc.ServiceDesc for Word2Animal service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Word2Animal_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "brainball.word2animal.Word2Animal",
	HandlerType: (*Word2AnimalServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAnimal",
			Handler:    _Word2Animal_GetAnimal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "word2animal.proto",
}
