// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: word2animal.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAnimalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *GetAnimalRequest) Reset() {
	*x = GetAnimalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_word2animal_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAnimalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnimalRequest) ProtoMessage() {}

func (x *GetAnimalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_word2animal_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnimalRequest.ProtoReflect.Descriptor instead.
func (*GetAnimalRequest) Descriptor() ([]byte, []int) {
	return file_word2animal_proto_rawDescGZIP(), []int{0}
}

func (x *GetAnimalRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type GetAnimalResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Animal     string  `protobuf:"bytes,1,opt,name=animal,proto3" json:"animal,omitempty"`           // e.g. "bird", "dog"
	Confidence float32 `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"` // optional; 0-1
}

func (x *GetAnimalResponse) Reset() {
	*x = GetAnimalResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_word2animal_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAnimalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnimalResponse) ProtoMessage() {}

func (x *GetAnimalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_word2animal_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnimalResponse.ProtoReflect.Descriptor instead.
func (*GetAnimalResponse) Descriptor() ([]byte, []int) {
	return file_word2animal_proto_rawDescGZIP(), []int{1}
}

func (x *GetAnimalResponse) GetAnimal() string {
	if x != nil {
		return x.Animal
	}
	return ""
}

func (x *GetAnimalResponse) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

var File_word2animal_proto protoreflect.FileDescriptor

var file_word2animal_proto_rawDesc = []byte{
	0x0a, 0x11, 0x77, 0x6f, 0x72, 0x64, 0x32, 0x61, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x15, 0x62, 0x72, 0x61, 0x69, 0x6e, 0x62, 0x61, 0x6c, 0x6c, 0x2e, 0x77,
	0x6f, 0x72, 0x64, 0x32, 0x61, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x22, 0x26, 0x0a, 0x10, 0x47, 0x65,
	0x74, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65,
	0x78, 0x74, 0x22, 0x4b, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6e, 0x69, 0x6d, 0x61,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x12,
	0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x64, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x64, 0x65, 0x6e, 0x63, 0x65, 0x32,
	0x6d, 0x0a, 0x0b, 0x57, 0x6f, 0x72, 0x64, 0x32, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x12, 0x5e,
	0x0a, 0x09, 0x47, 0x65, 0x74, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x12, 0x27, 0x2e, 0x62, 0x72,
	0x61, 0x69, 0x6e, 0x62, 0x61, 0x6c, 0x6c, 0x2e, 0x77, 0x6f, 0x72, 0x64, 0x32, 0x61, 0x6e, 0x69,
	0x6d, 0x61, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x62, 0x72, 0x61, 0x69, 0x6e, 0x62, 0x61, 0x6c, 0x6c,
	0x2e, 0x77, 0x6f, 0x72, 0x64, 0x32, 0x61, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x2e, 0x47, 0x65, 0x74,
	0x41, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x19,
	0x5a, 0x17, 0x62, 0x72, 0x61, 0x69, 0x6e, 0x62, 0x61, 0x6c, 0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_word2animal_proto_rawDescOnce sync.Once
	file_word2animal_proto_rawDescData = file_word2animal_proto_rawDesc
)

func file_word2animal_proto_rawDescGZIP() []byte {
	file_word2animal_proto_rawDescOnce.Do(func() {
		file_word2animal_proto_rawDescData = protoimpl.X.CompressGZIP(file_word2animal_proto_rawDescData)
	})
	return file_word2animal_proto_rawDescData
}

var file_word2animal_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_word2animal_proto_goTypes = []interface{}{
	(*GetAnimalRequest)(nil),  // 0: brainball.word2animal.GetAnimalRequest
	(*GetAnimalResponse)(nil), // 1: brainball.word2animal.GetAnimalResponse
}
var file_word2animal_proto_depIdxs = []int32{
	0, // 0: brainball.word2animal.Word2Animal.GetAnimal:input_type -> brainball.word2animal.GetAnimalRequest
	1, // 1: brainball.word2animal.Word2Animal.GetAnimal:output_type -> brainball.word2animal.GetAnimalResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_word2animal_proto_init() }
func file_word2animal_proto_init() {
	if File_word2animal_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_word2animal_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAnimalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_word2animal_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAnimalResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_word2animal_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_word2animal_proto_goTypes,
		DependencyIndexes: file_word2animal_proto_depIdxs,
		MessageInfos:      file_word2animal_proto_msgTypes,
	}.Build()
	File_word2animal_proto = out.File
	file_word2animal_proto_rawDesc = nil
	file_word2animal_proto_goTypes = nil
	file_word2animal_proto_depIdxs = nil
}
