# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import word2animal_pb2 as word2animal__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in word2animal_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class Word2AnimalStub(object):
    """Word2Animal is the gRPC service for mapping text to an animal identifier.
    Called by the API gateway (Go); client does not call this directly.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAnimal = channel.unary_unary(
                '/brainball.word2animal.Word2Animal/GetAnimal',
                request_serializer=word2animal__pb2.GetAnimalRequest.SerializeToString,
                response_deserializer=word2animal__pb2.GetAnimalResponse.FromString,
                _registered_method=True)


class Word2AnimalServicer(object):
    """Word2Animal is the gRPC service for mapping text to an animal identifier.
    Called by the API gateway (Go); client does not call this directly.
    """

    def GetAnimal(self, request, context):
        """GetAnimal returns the animal identifier for the given text.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Word2AnimalServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAnimal': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAnimal,
                    request_deserializer=word2animal__pb2.GetAnimalRequest.FromString,
                    response_serializer=word2animal__pb2.GetAnimalResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'brainball.word2animal.Word2Animal', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('brainball.word2animal.Word2Animal', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Word2Animal(object):
    """Word2Animal is the gRPC service for mapping text to an animal identifier.
    Called by the API gateway (Go); client does not call this directly.
    """

    @staticmethod
    def GetAnimal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/brainball.word2animal.Word2Animal/GetAnimal',
            word2animal__pb2.GetAnimalRequest.SerializeToString,
            word2animal__pb2.GetAnimalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
