# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: word2animal.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'word2animal.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11word2animal.proto\x12\x15\x62rainball.word2animal\" \n\x10GetAnimalRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"7\n\x11GetAnimalResponse\x12\x0e\n\x06\x61nimal\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x32m\n\x0bWord2Animal\x12^\n\tGetAnimal\x12\'.brainball.word2animal.GetAnimalRequest\x1a(.brainball.word2animal.GetAnimalResponseB\x17Z\x15\x62rainball/word2animalb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'word2animal_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\025brainball/word2animal'
  _globals['_GETANIMALREQUEST']._serialized_start=44
  _globals['_GETANIMALREQUEST']._serialized_end=76
  _globals['_GETANIMALRESPONSE']._serialized_start=78
  _globals['_GETANIMALRESPONSE']._serialized_end=133
  _globals['_WORD2ANIMAL']._serialized_start=135
  _globals['_WORD2ANIMAL']._serialized_end=244
# @@protoc_insertion_point(module_scope)
