"""Pixel art image assets - Stardew Valley-style 16x16 sprites."""

# Stardew Valley-inspired color palette (warm, earthy tones)
# Colors are RGB tuples (r, g, b)

# Define some common colors
TRANSPARENT = None  # Use None for transparent pixels
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
BROWN = (139, 90, 43)
DARK_BROWN = (101, 67, 33)
LIGHT_BROWN = (160, 120, 80)
PINK = (255, 192, 203)
DARK_PINK = (219, 112, 147)
GRAY = (128, 128, 128)
DARK_GRAY = (64, 64, 64)
LIGHT_GRAY = (192, 192, 192)
YELLOW = (255, 255, 0)
ORANGE = (255, 165, 0)
RED = (255, 0, 0)
GREEN = (0, 128, 0)
DARK_GREEN = (0, 100, 0)
BLUE = (0, 0, 255)
LIGHT_BLUE = (173, 216, 230)


def _create_cow_sprite():
    """Create a 16x16 cow sprite in Stardew Valley style."""
    # Simple cow sprite - white body with black spots
    sprite = [
        [TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT],
        [TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT],
        [TRANSPARENT, TRANSPARENT, TRANSPARENT, WHITE, WHITE, BLACK, WHITE, WHITE, WHITE, WHITE, BLACK, WHITE, WHITE, TRANSPARENT, TRANSPARENT, TRANSPARENT],
        [TRANSPARENT, TRANSPARENT, WHITE, WHITE, BLACK, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, BLACK, WHITE, WHITE, TRANSPARENT, TRANSPARENT],
        [TRANSPARENT, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, TRANSPARENT],
        [WHITE, WHITE, BLACK, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, BLACK, WHITE, WHITE],
        [WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE],
        [WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE],
        [WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE],
        [WHITE, WHITE, BLACK, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, BLACK, WHITE, WHITE],
        [WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE],
        [TRANSPARENT, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, TRANSPARENT],
        [TRANSPARENT, TRANSPARENT, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, TRANSPARENT, TRANSPARENT],
        [TRANSPARENT, TRANSPARENT, TRANSPARENT, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, TRANSPARENT, TRANSPARENT, TRANSPARENT],
        [TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT],
        [TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT],
    ]
    # Replace TRANSPARENT with background color (black) for rendering
    return [[pixel if pixel is not TRANSPARENT else BLACK for pixel in row] for row in sprite]


def _create_pig_sprite():
    """Create a 16x16 pig sprite in Stardew Valley style."""
    # Pink pig sprite
    sprite = [
        [TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT],
        [TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, PINK, PINK, PINK, PINK, PINK, PINK, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT],
        [TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT],
        [TRANSPARENT, TRANSPARENT, TRANSPARENT, PINK, PINK, BLACK, PINK, PINK, PINK, PINK, BLACK, PINK, PINK, TRANSPARENT, TRANSPARENT, TRANSPARENT],
        [TRANSPARENT, TRANSPARENT, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, TRANSPARENT, TRANSPARENT],
        [TRANSPARENT, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, TRANSPARENT],
        [PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK],
        [PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK],
        [PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK],
        [PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK],
        [TRANSPARENT, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, TRANSPARENT],
        [TRANSPARENT, TRANSPARENT, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, TRANSPARENT, TRANSPARENT],
        [TRANSPARENT, TRANSPARENT, TRANSPARENT, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, TRANSPARENT, TRANSPARENT, TRANSPARENT],
        [TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, PINK, PINK, PINK, PINK, PINK, PINK, PINK, PINK, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT],
        [TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT],
        [TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT],
    ]
    return [[pixel if pixel is not TRANSPARENT else BLACK for pixel in row] for row in sprite]


def _create_chicken_sprite():
    """Create a 16x16 chicken sprite in Stardew Valley style."""
    # White chicken with red comb
    sprite = [
        [TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT],
        [TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, RED, RED, RED, RED, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT],
        [TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, RED, RED, RED, RED, RED, RED, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT],
        [TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT],
        [TRANSPARENT, TRANSPARENT, TRANSPARENT, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, TRANSPARENT, TRANSPARENT, TRANSPARENT],
        [TRANSPARENT, TRANSPARENT, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, TRANSPARENT, TRANSPARENT],
        [TRANSPARENT, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, TRANSPARENT],
        [WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE],
        [WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE],
        [WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE],
        [TRANSPARENT, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, TRANSPARENT],
        [TRANSPARENT, TRANSPARENT, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, TRANSPARENT, TRANSPARENT],
        [TRANSPARENT, TRANSPARENT, TRANSPARENT, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, TRANSPARENT, TRANSPARENT, TRANSPARENT],
        [TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT],
        [TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT],
        [TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT],
    ]
    return [[pixel if pixel is not TRANSPARENT else BLACK for pixel in row] for row in sprite]


def _create_sheep_sprite():
    """Create a 16x16 sheep sprite in Stardew Valley style."""
    # White fluffy sheep
    sprite = [
        [TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT],
        [TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT],
        [TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT],
        [TRANSPARENT, TRANSPARENT, TRANSPARENT, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, TRANSPARENT, TRANSPARENT, TRANSPARENT],
        [TRANSPARENT, TRANSPARENT, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, TRANSPARENT, TRANSPARENT],
        [TRANSPARENT, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, TRANSPARENT],
        [WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE],
        [WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE],
        [WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE],
        [WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE],
        [TRANSPARENT, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, TRANSPARENT],
        [TRANSPARENT, TRANSPARENT, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, TRANSPARENT, TRANSPARENT],
        [TRANSPARENT, TRANSPARENT, TRANSPARENT, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, TRANSPARENT, TRANSPARENT, TRANSPARENT],
        [TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT],
        [TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT],
        [TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT],
    ]
    return [[pixel if pixel is not TRANSPARENT else BLACK for pixel in row] for row in sprite]


def _create_horse_sprite():
    """Create a 16x16 horse sprite in Stardew Valley style."""
    # Brown horse
    sprite = [
        [TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT],
        [TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT],
        [TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT],
        [TRANSPARENT, TRANSPARENT, TRANSPARENT, BROWN, BROWN, BLACK, BROWN, BROWN, BROWN, BROWN, BLACK, BROWN, BROWN, TRANSPARENT, TRANSPARENT, TRANSPARENT],
        [TRANSPARENT, TRANSPARENT, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, TRANSPARENT, TRANSPARENT],
        [TRANSPARENT, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, TRANSPARENT],
        [BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN],
        [BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN],
        [BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN],
        [BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN],
        [TRANSPARENT, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, TRANSPARENT],
        [TRANSPARENT, TRANSPARENT, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, TRANSPARENT, TRANSPARENT],
        [TRANSPARENT, TRANSPARENT, TRANSPARENT, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, TRANSPARENT, TRANSPARENT, TRANSPARENT],
        [TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT],
        [TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT],
        [TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT],
    ]
    return [[pixel if pixel is not TRANSPARENT else BLACK for pixel in row] for row in sprite]


# Pixel art dictionary - maps image keys to sprite data
PIXEL_ART_IMAGES = {
    "cow": _create_cow_sprite(),
    "pig": _create_pig_sprite(),
    "chicken": _create_chicken_sprite(),
    "sheep": _create_sheep_sprite(),
    "horse": _create_horse_sprite(),
}


def get_pixel_art_image(image_key: str):
    """
    Get pixel art image data by key.
    
    Parameters:
        image_key: Key for the image (e.g., "cow", "pig", "chicken")
        
    Returns:
        list: 2D array of RGB tuples, or None if key not found
    """
    return PIXEL_ART_IMAGES.get(image_key)


def get_all_image_keys():
    """Get all available image keys."""
    return list(PIXEL_ART_IMAGES.keys())
